tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "research"
owner = "ghrel"
authors = [{ username = "tbhb", signature = "Tony Burns" }]

[commit_types]
chore = { omit_from_changelog = true }
test = { omit_from_changelog = true }
